-- Tạo database với hỗ trợ Unicode
CREATE DATABASE QLSACH CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE QLSACH;

-- Bảng ACCOUNT
CREATE TABLE ACCOUNT (
	USERNAME		VARCHAR(50),
	PASSWORD		VARCHAR(255),
	TENTAIKHOAN		VARCHAR(255) CHARACTER SET utf8mb4,
	QUYEN			INT,
	KHOA_TK			INT,
	NGAYTAO                 DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (USERNAME, PASSWORD)
) CHARACTER SET utf8mb4;

-- Bảng KHACHHANG
CREATE TABLE KHACHHANG (
	MAKHACHHANG		VARCHAR(10) PRIMARY KEY,
	TENKHACHHANG	VARCHAR(255) CHARACTER SET utf8mb4,
	DIACHI			VARCHAR(255) CHARACTER SET utf8mb4,
	SDT				CHAR(10),
	DIEMTICHLUY		INT,
	USERNAME		CHAR(10)
) CHARACTER SET utf8mb4;

-- Bảng NHAXUATBAN
CREATE TABLE NHAXUATBAN (
	MANXB	VARCHAR(10) PRIMARY KEY,
	TENNXB	VARCHAR(50) CHARACTER SET utf8mb4,
	DIACHI	VARCHAR(255) CHARACTER SET utf8mb4,
	SDT		CHAR(10)
) CHARACTER SET utf8mb4;

-- Bảng THELOAI
CREATE TABLE THELOAI (
	MATHELOAI		VARCHAR(10) PRIMARY KEY,
	TENTHELOAI		VARCHAR(50) CHARACTER SET utf8mb4
) CHARACTER SET utf8mb4;

-- Bảng TACGIA
CREATE TABLE TACGIA (
	MATACGIA		VARCHAR(10) PRIMARY KEY,
	TENTACGIA		VARCHAR(50) CHARACTER SET utf8mb4
) CHARACTER SET utf8mb4;

-- Bảng SACH
CREATE TABLE SACH (
	MASACH			VARCHAR(10) PRIMARY KEY,
	TENSACH			VARCHAR(255) CHARACTER SET utf8mb4,
	GIAGOC			DOUBLE,
	SOLUONGTON		INT,
	ANHBIA			VARCHAR(255),
	NOIDUNG			VARCHAR(255),
	MATHELOAI		VARCHAR(10),
	MANXB			VARCHAR(10),
	MATACGIA		VARCHAR(10),
	FOREIGN KEY (MATHELOAI) REFERENCES THELOAI(MATHELOAI),
	FOREIGN KEY (MANXB) REFERENCES NHAXUATBAN(MANXB),
	FOREIGN KEY (MATACGIA) REFERENCES TACGIA(MATACGIA)
) CHARACTER SET utf8mb4;

-- Bảng DAILY
CREATE TABLE DAILY (
	MADAILY			VARCHAR(10) PRIMARY KEY,
	TEMDAILY		VARCHAR(50) CHARACTER SET utf8mb4,
	DIACHI			VARCHAR(255),
	SDT				CHAR(10)
) CHARACTER SET utf8mb4;

-- Bảng PHIEUNHAPSACH
CREATE TABLE PHIEUNHAPSACH (
	MAPHIEUNHAP		VARCHAR(10) PRIMARY KEY,
	NGAYLAP			DATE,
	TENNGUOILAP		VARCHAR(10) CHARACTER SET utf8mb4,
	THANHTIEN		DOUBLE,
	GHICHU			VARCHAR(255) CHARACTER SET utf8mb4,
	MADAILY			VARCHAR(10),
	FOREIGN KEY (MADAILY) REFERENCES DAILY(MADAILY)
) CHARACTER SET utf8mb4;

-- Bảng CHITIETPHIEUNHAP
CREATE TABLE CHITIETPHIEUNHAP (
	MAPHIEUNHAP		VARCHAR(10),
	MASACH			VARCHAR(10),
	SOLUONGNHAP		INT,
	DONGIANHAP		DOUBLE,
	PRIMARY KEY (MAPHIEUNHAP, MASACH),
	FOREIGN KEY (MAPHIEUNHAP) REFERENCES PHIEUNHAPSACH(MAPHIEUNHAP),
	FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
) CHARACTER SET utf8mb4;

-- Bảng HOADON
CREATE TABLE HOADON (
	MAHOADON		VARCHAR(10) PRIMARY KEY,
	NGAYLAP			DATE,
	THANHTIEN		DOUBLE,
	MAKHACHHANG		VARCHAR(10),
	FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)
) CHARACTER SET utf8mb4;

-- Bảng CTHOADON
CREATE TABLE CTHOADON (
	MAHOADON		VARCHAR(10),
	MASACH			VARCHAR(10),
	SOLUONGMUA		INT,
	DONGIABAN		DOUBLE,
	PRIMARY KEY (MAHOADON, MASACH),
	FOREIGN KEY (MAHOADON) REFERENCES HOADON(MAHOADON),
	FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
) CHARACTER SET utf8mb4;

-- Bảng GIOHANG
CREATE TABLE GIOHANG (
	MAKHACHHANG		VARCHAR(10),
	MASACH			VARCHAR(10),
	SOLUONGMUA		INT,
	DONGIABAN		DOUBLE,
	PRIMARY KEY (MAKHACHHANG, MASACH),
	FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
	FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
) CHARACTER SET utf8mb4;
